// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import { group } from "k6";
import "./requests/Data/Get-all.js";
import "./requests/Data/Get-one.js";
import "./requests/Data/Create.js";
import "./requests/Data/Update.js";
import "./requests/Data/Delete.js";
import "./requests/Data/Count.js";
import "./requests/Search/Create.js";
import "./requests/Search/Get-all.js";
import "./requests/Search/Get-one.js";
import "./requests/Search/Update.js";
import "./requests/Search/Delete.js";
import "./requests/Search/Search.js";
import "./requests/Search/Count.js";
import "./requests/Load/LoadRecord.js";

const N = 10000;

export let options = { 
  maxRedirects: 4, 
  vus: 10,
  iterations: N, 
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    logResponseTime: "false",
    logFailedRequest: "true",
    id: ""
  }
});

export default function() {
  // group("Data", function() {
  //   postman[Request]("Get all");
  //   postman[Request]("Get one");
  //   postman[Request]("Create");
  //   postman[Request]("Update");
  //   postman[Request]("Delete");
  //   postman[Request]("Count");
  // });
  // group("Search", function() {
  //   postman[Request]("Create", 2);
  //   postman[Request]("Get all", 2);
  //   postman[Request]("Get one", 2);
  //   postman[Request]("Update", 2);
  //   postman[Request]("Delete", 2);
  //   postman[Request]("Search");
  //   postman[Request]("Count", 2);
  // });
  group("Load", function() {
    postman[Request]("LoadRecord");
  });
}
