version: '3.4'

services:

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=dataengine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/dataengine-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - devnet

  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    networks:
      - devnet
    
networks:
  devnet:
    driver: bridge
    name: devnet_network
